import type { Metadata } from 'next'
import { Providers } from './providers'
import { Inter } from 'next/font/google'
import { NextIntlClientProvider, useMessages } from 'next-intl';
import NavBar from '@/components/navBar';
import '@/styles/squares.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Alejandro Ledesma Portfolio',
  description: 'Alejandro Ledesma Portfolio, generated by create next app',
}

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children, params
}: LocaleLayoutProps) {
  const messages = useMessages();

  return (
    <html lang={params.locale} suppressHydrationWarning>
      <body className={inter.className}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <Providers>

            <main className="h-screen w-full bg-transparent overflow-hidden">
              <div className="h-full w-full p-12 overflow-y-auto scrollbar-thin scrollbar-thumb-rounded-full scrollbar-thumb-sky-100 scrollbar-track-sky-400 dark:scrollbar-thumb-gray-700 dark:scrollbar-track-gray-900">
                <ul className="squares bg-gradient-to-t from-sky-200 to-sky-400 dark:from-zinc-900 dark:to-zinc-700">
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                </ul>
                <div className="flex flex-col mx-auto max-w-5xl">
                  <NavBar />
                  {children}
                </div>
              </div>
            </main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
